# For MSA -인식 문의
spring:
   application:
     name: server-editor
   config:
     import: optional:configserver:http://config:8888


# spring:
#   data:
#     mongodb:
#       uri: mongodb://localhost:27017/Editor